
export const page = {
  dashboard: {
    title: "Trang chủ",
  },
  statistic : {
    title:"Thống kê doanh thu",
  },
  staff_request : {
    title:"Yêu cầu nhận tiền",
  },
  customers: {
    title: "Thông tin khách hàng",
    searchPlaceholder: "Nhập từ tìm kiếm",
    tableColumns: [
      "Tên tài khoản",
      "Số dư tiền (VND)",
      "Số dư kim cương",
      "Trạng thái",
      "Hành động",
    ],
  },
  staffs: {
    title: "Thông tin cộng tác viên",
    searchPlaceholder: "Nhập từ tìm kiếm",
    buttonAdd: "Thêm cộng tác viên",
    buttonRequest: "Yêu cầu nhận tiền",
    tableColumns: [
      "Tên tài khoản",
      "Số dư (VND)",
      "Tỉ lệ nhận",
      "Trạng thái",
      "Hành động",
    ],
    tableStaffsRevenueColumns: [
      "Tên cộng tác viên",
      "Doanh thu (VND)",
      "Tỉ lệ nhận",
      "Mô tả",
    ],
    tableStaffsRequestsColumns: [
      "Số tiền (VND)",
      "Thời gian gửi đơn",
      "Ghi chú",
      "Trạng thái",
    ],
    tablePendingColumns: [
      "Tên tài khoản",
      "Số tiền (VND)",
      "Thời gian gửi đơn",
      "Ghi chú",
      "Hành động",
    ],
    tableCheckedColumns: [
      "Tên tài khoản",
      "Số tiền",
      "Thời gian gửi đơn",
      // "Thời gian xác nhận",
      "Ghi chú",
      "Trạng thái"
    ],
    formAdd: {
      title: "Thêm cộng tác viên",
      rate: "Tỷ lệ ",
      clientName: "Tên tài khoản",
      buttonSave: "Lưu",
      buttonRequest: "Gửi yêu cầu",
      buttonCancel: "Huỷ",
      buttonUpdate:"Cập nhập"
    },
    formRequest: {
      title:'Yêu cầu nhận tiền',
    }
  },
  diamond: {
    titlePending: "Đơn rút kim cương chờ duyệt",
    titleChecked: "Đơn rút kim cương đã duyệt",
    searchPlaceholder: "Nhập từ tìm kiếm",
    tablePendingColumns: [
      "Tên tài khoản",
      "Mã game",
      "Số kim cương rút",
      "Thời gian gửi đơn",
      "Hành động",
    ],
    tableCheckedColumns: [
      "Tên tài khoản",
      "Mã game",
      "Số kim cương rút",
      "Thời gian gửi đơn",
      "Thời gian xác nhận",
    ],
  },
  phoneCard: {
    titlePending: "Đơn thẻ cào chờ duyệt",
    titleChecked: "Đơn thẻ cào đã duyệt",
    searchPlaceholder: "Nhập từ tìm kiếm",
    tablePendingColumns: [
      "Tên tài khoản",
      "Nhà mạng",
      "Giá trị thẻ (VND)",
      "Mã thẻ",
      "Số serial",
      "Thời gian nạp",
      "Hành động",
    ],
    tableCheckedColumns: [
      "Tên tài khoản",
      "Nhà mạng",
      "Giá trị thẻ (VND)",
      "Mã thẻ",
      "Số serial",
      "Thời gian nạp",
      "Thời gian xác nhận",
      "Trạng thái"
    ],
  },
  atmCard: {
    title: "Danh sách nạp ATM",
    searchPlaceholder: "Nhập từ tìm kiếm",
    tableColumns: [
      "Tên tài khoản",
      "Giá trị nạp (VND)",
      "Tỷ lệ nạp",
      "Nội dung chuyển khoản",
      "Thời gian nạp",
    ],
  },
  accountGame: {
    title: "Danh sách tài khoản game",
    searchPlaceholder: "Nhập từ tìm kiếm",
    addNewAccount: "Thêm mới",
    addNewAccounts: "Thêm mới nhiều",
    tableSellingColumns: [
      "Ảnh",
      "Rank",
      "Tên tài khoản",
      "Mật khẩu",
      "Danh mục",
      "Giá (VND)",
      "Mức giảm (%)",
      "Người đăng",
      "Trạng thái",
      "Hành động",
    ],
    tableSoldColumns: [
      "Ảnh",
      "Rank",
      "Tên tài khoản",
      "Mật khẩu",
      "Danh mục",
      "Giá (VND)",
      "Mức giảm (%)",
      "Người đăng",
      "Trạng thái",
      "Thời gian bán",
    ],
    formAdd: {
      title: "Cài đặt tài khoản",
      category: "Danh mục tài khoản",
      typeGame: "Loại game",
      typeLogin: "Kiểu đăng nhập",
      username: "Tên tài khoản",
      password: "Mật khẩu",
      code: "Mã tài khoản",
      rank: "Rank tài khoản",
      accountName: "Tên tài khoản",
      accountId: "Mã tài khoản",
      urlImg: "Ảnh tài khoản",
      description: "Mô tả",
      price: "Giá bán (VND)",
      discount: "Mức giảm (%)",
      status: "Trạng thái",
      action: "Hành động",
      buttonSave: "Lưu",
      buttonUpdate: "Cập nhật",
      buttonCancel: "Huỷ",
    },
  },
  transaction: {
    title: "Cộng/Trừ tiền",
    searchPlaceholder: "Nhập từ tìm kiếm",
    tableColumns: [
      "Tên tài khoản",
      "Loại",
      "Lý do",
      "Số tiền (VND)",
      "Thời gian tạo",
    ],
    buttonAdd: "Tạo mới",
    formAdd: {
      title: "Cộng/Trừ tiền",
      type: "Loại",
      clientName: "Tên tài khoản",
      money: "Số tiền",
      reason: "Lý do",
      buttonSave: "Lưu",
      buttonCancel: "Huỷ",
    },
  },
  flashSale: {
    title: "Cài đặt flash sale",
    searchPlaceholder: "Nhập từ tìm kiếm",
    tableColumns: [
      "Ngày flash sale",
      "Giờ bắt đầu",
      "Giờ kết thúc",
      "Hành động",
    ],
    buttonAdd: "Tạo mới",
    formAdd: {
      title: "Cài đặt flash sale",
      nameProgram: "Tên chương trình",
      status: "Trạng thái",
      startDate: "Ngày bắt đầu",
      endDate: "Ngày kết thúc",
      startTime: "Giờ bắt đầu",
      endTime: "Giờ kết thúc",
      accountName: "Tên tài khoản",
      accountId: "Mã tài khoản",
      urlImg: "Ảnh",
      description: "Mô tả",
      price: "Giá bán (VND)",
      discount: "Mức giảm (%)",
      action: "Hành động",
      buttonSave: "Lưu",
      buttonUpdate: "Cập nhật",
      buttonCancel: "Huỷ",
    },
  },
  categories: {
    title: "Quản lí danh mục",
    searchPlaceholder: "Nhập từ tìm kiếm",
    tableColumns: [
      "Tên danh mục",
      "Loại",
      "Số tài khoản chưa bán",
      "Số tài khoản đã bán",
      "Giá chung (VND)",
      "Mức giảm  (%)",
    ],
    buttonAdd: "Tạo mới",
    formAdd: {
      titleForm: "Cài đặt danh mục",
      type: "Loại danh mục",
      title: "Tên danh mục",
      thumbnailUrl: "Ảnh danh mục",
      description: "Mô tả",
      guide: "Hướng dẫn",
      price: "Giá chung (VND)",
      discount: "Mức giảm (%)",
      buttonSave: "Lưu",
      buttonUpdate: "Cập nhật",
      buttonCancel: "Huỷ",
    },
  },
  lucky: {
    title: "Danh sách vòng quay may mắn",
    searchPlaceholder: "Nhập từ tìm kiếm",
    tableColumns: [
      "Tên vòng quay",
      "Mô tả",
      "Hành động",
    ],
    tableHistoryColumns: [
      "Tên khách hàng",
      "Tên vòng quay",
      "Giá (VND)",
      "Loại trúng thưởng",
      "Phần thưởng (Số KC/ Mã Acc game)",
      "Thời gian chơi",
    ],
    buttonAdd: "Tạo mới",

  },
  flipCard: {
    title: "Danh sách game lật thẻ",
    searchPlaceholder: "Nhập từ tìm kiếm",
    tableColumns: [
      "Tên game",
      "Mô tả",
      "Hành động",
    ],
    tableHistoryColumns: [
      "Tên khách hàng",
      "Tên game",
      "Giá (VND)",
      "Loại trúng thưởng",
      "Phần thưởng (Số KC/ Mã Acc game)",
      "Thời gian chơi",
    ],
    buttonAdd: "Tạo mới",

  },
  login: {
    title: "Đăng nhập",
    titleRegister: "Đăng ký",
    welcome: "Hãy đăng nhập và tiếp tục sử dụng trang web.",
    registerMess: "Hãy đăng ký tài khoản và thoả thích trải nghiệm",
    labelUsername: "Tên tài khoản",
    labelPassword: "Mật khẩu",
    placeHolderUsername: "Nhập tên tài khoản",
    placeHolderPassword: "Nhập mật khẩu",
    errorUsername: "Hãy nhập tên tài khoản!",
    errorPassword: "Hãy nhập mật khẩu!",
    forgotPassword: "Quên mật khẩu?",
    button: "Đăng nhập",
    buttonRegister: "Đăng ký",
  },
};
